EVA_VERSION="Development 1.5"

WINDOW_HEIGHT=720
WINDOW_WIDTH=1280
WINDOW_PADDING=50
WINDOW_HEIGHT_PADDING=WINDOW_HEIGHT - WINDOW_PADDING
WINDOW_WIDTH_PADDING=WINDOW_WIDTH - WINDOW_PADDING

GRID_PADDING=10